compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs

# Allow installs that would update the lockfile (useful on Vercel build)
enableImmutableInstalls: false
